### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by arnaudgelas** [Archie3d/qpdf#1]
Hi,

I would like to know under which license do you release this small piece of code, please?

Thanks,
Arnaud

**Comment by Archie3d** [comment]
Hello Arnaud,

Since it depends on Qt (LGPL) and PDF.js (Apache), I put the LGPL license on it, meaning you can compile it and link dynamically and free to use and distribute in commercial applications, the same way as Qt.

Kind regards,

Arthur.
