### ISSUE TITLE
help on a sample project.

### ISSUE THREAD

**Issue by rahmanshaber** [Archie3d/qpdf#10]
i am in linux. qt5.10.1.
i tried to make a sample project with qpdf lib with designer(not with code)
made new ui/cpp/h .added a layout and added this lines in conostrector .

`
m_pPdfWidget = new QPdfWidget();
ui->layout->addWidget(m_pPdfWidget);
QString filePath = QString::fromLatin1("/home/shaber/Desktop/c.pdf");
m_pPdfWidget->loadFile(filePath);

`
pdf widget shows just fine.but the given pdf is not showing.
opening pdf with the folder icon within the pdfwidget working fine.

![o](https://user-images.githubusercontent.com/30831735/39813450-5143c88a-53b2-11e8-96e8-1807c4975a27.png)

here is the application output.

`[0509/175601.963406:WARNING:stack_trace_posix.cc(648)] Failed to open file: /home/shaber/#272223 (deleted)
  Error: No such file or directory
qt5ct: using qt5ct plugin
QMetaObject::connectSlotsByName: No matching signal for on_open_clicked()
js: The provided value 'moz-chunked-arraybuffer' is not a valid enum value of type XMLHttpRequestResponseType.
js: Failed to load file:///home/shaber/Desktop/c.pdf: Cross origin requests are only supported for protocol schemes: http, data, chrome, https.
js: Uncaught TypeError: Cannot read property 'onProgressiveData' of undefined
js: Uncaught TypeError: Cannot read property 'reject' of undefined`

i think i need to add the code in main.cpp that you added in your one .but i don't want any command line support.
so how i solve this problem.
please help me.

**Comment by Archie3d** [comment]
Hi,
Indeed, this is due to the web browser security policy not letting you load a local file.
You have to pass `--disable-web-security` option [like in the example](https://github.com/Archie3d/qpdf/blob/master/pdfviewer/main.cpp). This won't require any command line options to be passed to an executable, because the option is injected in runtime from within the `main()` function.

Alternatively, you can use `loadData(QByteArray)` instead of `loadFile(QString)` method. In this case you'll have to read a pdf into `QByteArray` first and then pass it to `loadData()` method. This will not require browser security alteration, but it will impose pdf file size limitation (very large PDF file will fail to load).

**Comment by rahmanshaber** [comment]
anyway to --disable-web-security in contractor?

and i really don't know how to use loadData(QByteArray) to load the pdf

**Comment by Archie3d** [comment]
You have to pass `--disable-web-security` to [QApplication](http://doc.qt.io/qt-5/qapplication.html) constructor, exactly like in  [main.cpp](https://github.com/Archie3d/qpdf/blob/ea546ba24305153e21b899ec08aa16af041d815b/pdfviewer/main.cpp#L24)

Alternatively:
```cpp
QFile f("/path/to/document.pdf");
if (f.open(QIODevice::ReadOnly)) {
    QByteArray data = f.readAll();
    pPdfWidget->loadData(data);
    f.close();
}
```

**Comment by rahmanshaber** [comment]
thanks for the solutions.
i am going with the QByteArray solution.

is ther any way to set the page to "Page Fit" on startup??
and did this to hide the toolbar.but not working
`m_pPdfWidget->setToolbarVisible(false);`

**Comment by rahmanshaber** [comment]
hello .
sorry to bother you.
is there any solution to hide the toolbar.
also i want to know is ther any way to get the pdf properties in a qtexbrowser?

**Comment by Archie3d** [comment]
There is [QPdfWidget::setToolbarVisible(bool)](https://github.com/Archie3d/qpdf/blob/ea546ba24305153e21b899ec08aa16af041d815b/qpdflib/qpdfwidget.h#L131) method, which you can use to hide the toolbar.

In order to get pdf properties, additional bridging code is required to bring those from JavaScript into C++. Currently there is no method to get pdf document properties, but this should be relatively easy to add.

**Comment by rahmanshaber** [comment]
did that to hide the tool-bar. but not working.

**Comment by Archie3d** [comment]
Hi
I've just [pushed a fix to address the toolbar visibility toggle](https://github.com/Archie3d/qpdf/issues/11).

**Comment by rahmanshaber** [comment]
nope .
still showing the pdfwidget toolbar.
![u](https://user-images.githubusercontent.com/30831735/40097403-c97f6a58-58f7-11e8-92ef-fe17c532dd41.png)

and will you do anything to get the properties in a qstringlist?

**Comment by Archie3d** [comment]
You are using it wrong. Please see the #11 issue. You can toggle visibility
only after the widget has been initialized. If you do this before, the web
page is not loaded yet, so it won’t have any effect. Observe
QPdfWidget::initialized() signal, and change visibility only when it’s been
emitted.

**Comment by rahmanshaber** [comment]
did this in constractor's last line and onOpenfile() function 
`QPdfWidget *pPdf = new QPdfWidget();
    connect(pPdf, &QPdfWidget::initialized, [=]() {
        pPdf->setToolbarVisible(false);
    });`
nothing.

**Comment by Archie3d** [comment]
You have to do this on your `m_pPdfWidget` you create in `MainWindow` constructor:
```cpp
m_pPdfWidget = new QPdfWidget();
connect(m_pPdfWidget, &QPdfWidget::initialized, [this]() {
    m_pPdfWidget->setToolbarVisible(false);
});
```

**Comment by rahmanshaber** [comment]
please can you point me what i am doing wrong?
[corepdf](https://github.com/rahmanshaber/corepdf/blob/master/corepdf/corepdf.cpp)

thanks.

**Comment by Archie3d** [comment]
You do not need [line 28](https://github.com/rahmanshaber/corepdf/blob/618fde013f2824117a7a3152fdc39be540a8e368/corepdf/corepdf.cpp#L28) anymore. Also don't load file before widget has been initialized ([lines 32-37](https://github.com/rahmanshaber/corepdf/blob/618fde013f2824117a7a3152fdc39be540a8e368/corepdf/corepdf.cpp#L32)), but move it to `QPdfWidget::initialized()` signal handler, like so:
```cpp
connect(PdfWidget, &QPdfWidget::initialized, [this]() {
    PdfWidget->setToolbarVisible(false);
    QFile f(path);
    if (f.open(QIODevice::ReadOnly)) {
        QByteArray data = f.readAll();
        PdfWidget->loadData(data);
        f.close();
    }
});
```
I've tried your code, and it works fine to me. But I ran on Windows, maybe it behaves differently on Linux - can try later.

**Comment by rahmanshaber** [comment]
thanks.
but getting this.
![q](https://user-images.githubusercontent.com/30831735/40173702-80591aba-59f4-11e8-98f5-d907524f13f9.png)

and any plans on doing a bridge in properties??

**Comment by Archie3d** [comment]
Well, that's because you do not capture your path variable when passing it to lambda:
```cpp
connect(PdfWidget, &QPdfWidget::initialized, [this, path]() {
    PdfWidget->setToolbarVisible(false);
    QFile f(path);
    if (f.open(QIODevice::ReadOnly)) {
        QByteArray data = f.readAll();
        PdfWidget->loadData(data);
        f.close();
    }
});
```

**Comment by rahmanshaber** [comment]
thanks. it works.
is there any way to disable any links(web page) that are in pdf??

**Comment by Archie3d** [comment]
That I do not know. You can disable this on QtWebEngine level browser, or in pdf.js itself. [Here is one way of disabling hyperlinks.](https://stackoverflow.com/questions/31053948/how-to-disable-hyperlinks-within-a-pdf-rendered-by-pdf-js?rq=1)
