### ISSUE TITLE
licensing issue 

### ISSUE THREAD

**Issue by rahmanshaber** [Archie3d/qpdf#12]
the problem is i will include [this corepdf](https://github.com/rahmanshaber/corepdf) in my app [CoreBox](https://github.com/rahmanshaber/corebox).
for this i need one qmake for my main app that could include all the cpp and header file including corepad's library.

so my consernt is that if i include the library in the same qmake , is there any problem??
like this
 `
TEMPLATE = app

CONFIG += c++11

QT += widgets\
      webengine\
      webenginecore\
      webenginewidgets\
      webchannel

HEADERS += corepdf.h\
    qpdflib/pdfjsbridge.h \
    qpdflib/qpdf.h \
    qpdflib/qpdfwidget.h \

SOURCES += \
    corepdf.cpp \
    main.cpp \
    qpdflib/pdfjsbridge.cpp \
    qpdflib/qpdfwidget.cpp \

RESOURCES += \
    qpdflib/pdfview.qrc
 `

**Comment by rahmanshaber** [comment]
hello .
sorry to bother you again .
my app release in on hold for this.
my concern about licensing of the library.
i asked it in qt forum .they said , it's ok.
but i need your statement.

i have no choice with out your library.
i said the user that i will include a pdf viewer.
if you say no , i have to release my app without it.and that will be a big issue for me.

i hope you understood the issue.
thanks for all the help.

**Comment by Archie3d** [comment]
Hi,
It’s ok, no problem. But if you don’t want your project to become lgpl you should have compiled qpdf into a library, and then link it dynamically distributing the dll, like you do with Qt.

**Comment by rahmanshaber** [comment]
thank you very much.
i tried to do compiled library and then link it dynamically .
but problem is , if app compiled in different architecture.

is my whole app will be a lgpl or not??

**Comment by Archie3d** [comment]
There should be no problem building it for different architecture (if the viewer example, which links qpdf dynamically, works for your target architecture - yours should work as well).
If you link statically, then you have to be lgpl (the same as with Qt, which is also lgpl). If you link dynamically (dll, so, dylib), then you can license your application as you wish.

**Comment by rahmanshaber** [comment]
ok. understood
