### ISSUE TITLE
close opened pdf properly 

### ISSUE THREAD

**Issue by rahmanshaber** [Archie3d/qpdf#13]
how can i close the opened pdf??

in my app i added the qdfwidget .
when i close the qdfwidget , it crashes the whole app .
i think i need to close the qdfwidget properly.

i tried 
` void corepdf::eclose(){
    QPdfWidget *cpdf = this->findChild<QPdfWidget*>("QPdfWidget");
    cpdf->close();
}

`

.but qdfwidget not closing .

how can i close qdfwidget properly??

**Comment by Archie3d** [comment]
It should close the document. But because of conflict with `QWidget::close()` method, I've just renamed it to `QPdfWidget::closeDocument()`. It closes the document and resets the view to a default empty one.

**Comment by rahmanshaber** [comment]
still not closing.it crashes the whole app.
can include the methode in your viewer??

here is my code

`
     corepdf::corepdf(QWidget *parent):QWidget(parent)
     {
     //    openPdfFile("/home/shaber/Desktop/p.pdf");

        setObjectName("corepdf");
        setStyleSheet("QWidget{background-color: #3E3E3E;border: 1px #2A2A2A;}");
     }

     corepdf::~corepdf()
     {
        delete PdfWidget;
     }

     void corepdf::eclose()
     {
        QPdfWidget *cpdf = this->findChild<QPdfWidget*>("QPdfWidget");
        cpdf->closeDocument();
     }

     void corepdf::openPdfFile(const QString path)
     {
        workFilePath = path;
        QVBoxLayout * mainLayout = new QVBoxLayout();
        PdfWidget = new QPdfWidget();

        connect(PdfWidget, &QPdfWidget::initialized, [this,path]() {
            PdfWidget->setToolbarVisible(false);
            QFile f(path);
            if (f.open(QIODevice::ReadOnly)) {
                QByteArray data = f.readAll();
                PdfWidget->loadData(data);
                f.close();
            }
        });

        cShot     = new QPushButton("close");
        connect(cShot,SIGNAL(clicked()),this,SLOT(eclose()));
        mainLayout->setContentsMargins(0,0,0,0);
        mainLayout->addWidget(PdfWidget);
        mainLayout->addWidget(cShot);
        setLayout(mainLayout);
     }
`


`
     //header
     class corepdf : public QWidget
     {
        Q_OBJECT

     public:
        corepdf(QWidget *parent = 0);
        ~corepdf();
        void openPdfFile(const QString path);


        QString workFilePath;

     protected:
        void closeEvent(QCloseEvent *event);
     public slots:
        void eclose();
     private:
 
        QPushButton * cShot;
        QPdfWidget *PdfWidget;
     };
`

**Comment by Archie3d** [comment]
Are you sure the following code of yours
```cpp
QPdfWidget *cpdf = this->findChild<QPdfWidget*>("QPdfWidget");
```
does not return null? Because you never assign "QPdfWidget" name to your widget.

Try adding the following when creating the widget:
```cpp
QVBoxLayout * mainLayout = new QVBoxLayout();
PdfWidget = new QPdfWidget(); // BTW, do you really want to create a new widget every time you open a file?
PdfWidget->setObjectName("QPdfWidget"); // Without the name assignment findWidget() won't find anything
```

Or better create your PdfWidget in constructor and access it via member variable of your `corepdf` class.

**Comment by rahmanshaber** [comment]
i can't add qpdfwidget in constructor .
there is some ui problem.

i added the object name .but still closing qpdfwidget is crashing the whole app.
i don't know how to check ,if the widget is found or not.

**Comment by Archie3d** [comment]
Well, you check it against `nullptr`:
```cpp
 void corepdf::eclose()
 {
    QPdfWidget *cpdf = this->findChild<QPdfWidget*>("QPdfWidget");
    if (cpdf != nullptr) {
        cpdf->closeDocument();
    } else {
        qWarning() << "Not found!";
    }
 }
```

**Comment by rahmanshaber** [comment]
yes . widget is not found.

![ge](https://user-images.githubusercontent.com/30831735/40403104-6bc205d6-5e71-11e8-8b0c-7feb7b72ac54.png)

**Comment by rahmanshaber** [comment]
i found the solution .
`QPdfWidget *cpdf = qobject_cast<QPdfWidget*>(this->children().at(1));`

**Comment by Archie3d** [comment]
This is not a good solution, which will break when you start changing the layout or add more children QObjects to your `corepdf`. I would recommend to capture `cpdf` pointer as a class member field instead.
