### ISSUE TITLE
[Feature Request] add some feature 

### ISSUE THREAD

**Issue by rahmanshaber** [Archie3d/qpdf#15]
i have some feature request.

1. add a option to turn off the hyper-link form qpdfwidget .
2. get a pdf page as a pixmap (picture) .
3. and add a close method in example app.
4. get the pdf properties in text (qtextbrowser).
5. add version naming .
6. disable the print button as it's not able to do anything.
7. and add option to select the zoom value in startup.

i hope this feature is relevant to qpdf and get this in next release.

**Comment by Archie3d** [comment]
1. Should be possible
2. Not sure - have to check whether QtWebEngine can render itself into an image.
3. Easy
4. Should be feasible as well
5. ???
6. Indeed, but the ability to print depends on the WebView implementation handling print event.
7. There are methods `QPdfWidget::zoomIn()` and `QPdfWidget::zoomOut()`. Zoom level can be adjusted after a document has been loaded though.

**Comment by rahmanshaber** [comment]
1.thanks
2.thanks.hoping to get it.
3.great
4.great.
5.like give the library a version to follow the devlopment.
6.print event is useless in the pdf(i think).it is a miss leading button in pdfwidget.(also i think)
7.i know that .i am talking about this - fit the page ,fit width , fit height.

8.also i u can add dual page view from [here](https://github.com/mozilla/pdf.js/issues/590).very lat one.
as i have no knowledge about css
