### ISSUE TITLE
QWidget: Must construct a QApplication before a QWidget

### ISSUE THREAD

**Issue by sbonnefoy** [Archie3d/qpdf#29]
Hello, I use qpdf in my application since some months ago. Everything worked fine but I'd like to switch my application from x86 to x64.

If I build the qpdf library with Qt_5_12_7_MSVC2017_64bit-**Debug** kit:
-> My application works fine in **debug mode**; I'm able to load pdf file
-> My application doesn't work in **release mode**;  I get this error: **QWidget: Must construct a QApplication before a QWidget**
![release](https://user-images.githubusercontent.com/61426949/132505829-e23ebbb6-855d-451c-a0da-d17af01016fe.png)

If I build the qpdf library with Qt_5_12_7_MSVC2017_64bit-**Realease** kit:
-> My application doesn't work in **debug mode**;  I'm not able to load pdf and I get this error:
Resource :/pdfview/pdf.js not found or is empty
Resource :/pdfview/viewer.js not found or is empty
Uncaught ReferenceError: qpdf_Initialize is not defined

-> My application doesn't work in **release mode**;  I'm not able to load pdf and I get this error:
Resource :/pdfview/pdf.js not found or is empty
Resource :/pdfview/viewer.js not found or is empty
Uncaught ReferenceError: qpdf_Initialize is not defined

As you can see it works in debug mode when the library is built in debug mode too.
But I'd like to build my application in release mode.
Do you have any idea from where the problem could come from? Thanks a lot for your help.

**Comment by Archie3d** [comment]
Hi, you need to disable the Qt Quick Compiler (see the readme about this). If not disabled the *.js get interpreted as QT Quick scripts for some reason, and then don't get into the plain resources.

**Comment by sbonnefoy** [comment]
Thanks a lot for your quick reply @Archie3d
Ok I found it's fully my fault... I noticed your readme but I disabled it in my own application using the library... not when I built the library itself.
Thanks a lot for your support I really appreciated and and thank you for your work on this project ;)

**Comment by Archie3d** [comment]
My pleasure! 😀
