### ISSUE TITLE
Now it only render default file pdf 

### ISSUE THREAD

**Issue by trungbui94** [Archie3d/qpdf#3]
I found that QPdfWidget::renderPdf() call to unknow javascript function "showPDFFile" then the application will show a default file ?
Which method i can use to show a specific PDF file ? 
Tks.

**Comment by Archie3d** [comment]
Hi,

1. You are not supposed to call QPdfWidget::renderPdf(), it is private and used internally. Instead you have to call QPdfWidget::loadFile(const QString &path);
2. showPdfFile() function is defined in viewer.js at the very end of the file (please mind the case, it is not showPDFFile!) But you should not care about this function anyway, as it is not a part of QPdfWidget's public interface.

Cheers,
Arthur.

**Comment by trungbui94** [comment]
Tks you for replying me, yes i find that the project from current github repo is actually have "showPdfFile" function. I don't realize that my downloaded project in local is not the same as your project(It's downloaded from another site). I'll check it again.
