### ISSUE TITLE
Error on using qpdf.lib on vs 2019

### ISSUE THREAD

**Issue by ehsanr1366** [Archie3d/qpdf#30]
I build <qpdflib> on qtcreator and vs 2019. 

When I want to use of qpdf.lib like example, I get this error on build (debugx64):

 error C2491: 'QPdfWidget::staticMetaObject': definition of dllimport static data member not allowed

**Comment by Archie3d** [comment]
You are probably not compiling it right. Make sure that `QPDFLIB_BUILD` is defined when compiling `qpdf.lib`, and **not defined** when linking the library (and the includes) into an application.
See how it's done in [qpdflib.pro](https://github.com/Archie3d/qpdf/blob/master/qpdflib/qpdflib.pro) and in [pdfviewer.pro](https://github.com/Archie3d/qpdf/blob/master/pdfviewer/pdfviewer.pro).

**Comment by ehsanr1366** [comment]
Is there a point in building and using a static library?

on readme:

```This qmake-based project defines two build targets: qpdf shared library, and an example PDF viewer (pdfviewer) based on qpdf library. Should yoo want to integrate a PDF view into your project, you need to take qpdf library only, you do not need pdfviewer (though you may use it as inspirational example for your project). So you may copy qpdflib into your project and build it as a shared library to be linked with your code.```
Tnks

**Comment by Archie3d** [comment]
There is no static library built. The qpdf.lib created is a companion library for the qpdf.dll. This lib contains the exported symbols from the DLL just to be linked with your application. The readme tells about integrating the `qpdflib` source code folder into your project, so that it gets compiled and linked with your application.

**Comment by ehsanr1366** [comment]
ok thank you
