### ISSUE TITLE
Scrolling/Zooming issues

### ISSUE THREAD

**Issue by DerDakon** [Archie3d/qpdf#6]
I used a slightly modified version of the pdfviewer example with a red background so I can easily see the exact dimension of the QPdfWidget instance, otherwise it is the exact code from the repository.

Initially a PDF is shown ![20171005_143537](https://user-images.githubusercontent.com/10909049/31264134-6d39093c-aa67-11e7-9989-81e9368de8de.jpg)
 on a device with touchscreen, and everything compiled with Qt 5.9.1. Then I used a pinch gesture to shrink the PDF contents. However the area of the rendering shrinked with it I would have expected it to still use the full height of the QPdfWidget, showing more than the initial half page.
![20171005_143552](https://user-images.githubusercontent.com/10909049/31264170-9f75b684-aa67-11e7-9a1d-98bd9143b074.jpg)

If I then use a scroll gesture it depends on the location of the gesture inside the QPdfWidget which behavior I get:

 - scrolling on the right side (grey area) of the widget moves the draw area as seen in the example, I moved up the PDF drawing by half the size
![20171005_143641](https://user-images.githubusercontent.com/10909049/31264200-be4fbd0c-aa67-11e7-81f6-776c02ecbe55.jpg)

 - scrolling on the draw area actually moves the contents of the PDF as I would have expected for the other action, too

**Comment by Archie3d** [comment]
Hi. Have you tried QWebEngineView showing any html content? Does it zooms/scrolls alright for you?

**Comment by DerDakon** [comment]
Yes, that works fine.

**Comment by Archie3d** [comment]
I'll update the project to the latest pdf.js, see if this will make any difference.
