### ISSUE TITLE
An error occurred while loading the PDF

### ISSUE THREAD

**Issue by dingsh** [Archie3d/qpdf#8]
I'm running the project with win7, 32bits, Qt5.6.0 msvc.
It could run successful, but it could not open any PDF and show massage like this 
![image](https://user-images.githubusercontent.com/10463664/37507023-9a16dd50-2927-11e8-9ec8-765b67225c8a.png)

May I ask how can I open some PDF files.
Thank you very much.

**Comment by Archie3d** [comment]
Qt 5.6.0 has some issues with WebEngine. You may try using the debugger (see https://doc.qt.io/qt-5.6/qtwebengine-debugging.html) in order to get more insights.

Also, could you try later version (5.8 or 5.9)? These I know should work correctly.

**Comment by dingsh** [comment]
Thanks for your help! I run it successfully with qt5.8.
Now I want to add the pdfviewer to my project, How can I complete that work?

Now I am doing like this
first new Subdirectory project, and then new my project,
second copy pdflib folder into the project. 
and then edit the pro file 
![image](https://user-images.githubusercontent.com/10463664/37636546-bd5caa62-2bfa-11e8-904d-3afb22f66f78.png)

and then Add internal library
![image](https://user-images.githubusercontent.com/10463664/37636696-75b9b640-2bfb-11e8-8318-2bd6968b4257.png)

This is my file tree

![image](https://user-images.githubusercontent.com/10463664/37636689-6d937262-2bfb-11e8-9455-d2d7b96c4b60.png)

I can not #include "QPdfWidget" beacuse it will show like this 

qt C1083: 无法打开包括文件: “QPdfWidget”: No such file or directory

"无法打开包括文件" means can not open include file 


May I ask for your help to deal this problem. Thank you!

**Comment by Archie3d** [comment]
Hi. In your qt_pdfp_test.pro you need to specify the include path:
```
INCLUDEPATH += ../qpdflib
```
Check [pdfviewer.pro](https://github.com/Archie3d/qpdf/blob/master/pdfviewer/pdfviewer.pro) (you may wish to use it as template for your project).

**Comment by dingsh** [comment]
Hi, 
This is qt_pdfp_test.pro
![image](https://user-images.githubusercontent.com/10463664/37689743-bf8a61b8-2c9e-11e8-8d58-c3ee7595b78b.png)



After I  Add internal library ,the message in red is created automatic

And this is pdfviewer.pro,I do not edit anything.

![image](https://user-images.githubusercontent.com/10463664/37689852-6d4d9e82-2c9f-11e8-94fe-9294d35a9c88.png)

Thank you!

**Comment by Archie3d** [comment]
It looks alright. Did you try to rerun qmake? (After any changes in .pro files you need to rerun qmake).

**Comment by dingsh** [comment]
OK, I forget to rerun qmake, It could run now.
How could I set pdf file path with code？
I could not open pdf file with code like this 
![image](https://user-images.githubusercontent.com/10463664/37690983-851250ba-2ca6-11e8-9af7-3aa425eb2620.png)

Thanks for your help.

**Comment by Archie3d** [comment]
Make sure you pass "--disable-web-security" command line argument to your QApplication. See [pdfviewer main.cpp](https://github.com/Archie3d/qpdf/blob/master/pdfviewer/main.cpp) for details. Otherwise the embedded web browser will refuse to load local files.

**Comment by dingsh** [comment]
Great!
I made it successful.
Thanks for your help!
