### ISSUE TITLE
please update the lib

### ISSUE THREAD

**Issue by rahmanshaber** [Archie3d/qpdf#9]
please update the pdf.js to latest one .
 as it has many bug fixes

**Comment by Archie3d** [comment]
The project is already at the latest released pdf.js [1.9.426](https://github.com/mozilla/pdf.js/releases/tag/v1.9.426). Next [v1.10.88](https://github.com/mozilla/pdf.js/releases/tag/v1.10.88) is still is pre-release as for this moment.

**Comment by rahmanshaber** [comment]
sorry,got that.
can you add the next and previous button in toolbar.
i could not figure it out.

**Comment by Archie3d** [comment]
What do you mean by next and previous buttons? There are next page and previous page buttons...
The library embeds standard [pdf.js viewer](https://mozilla.github.io/pdf.js/web/viewer.html), with all the functionality it provides (except printing).

**Comment by rahmanshaber** [comment]
i know it has next and previous buttons.but the are in pdf.js.
i want to know how the goto next page by a button from qt button(in app's toolbar)

**Comment by Archie3d** [comment]
There are
`int page()`
`void setPage(int)`
methods in [QPdfWidget](https://github.com/Archie3d/qpdf/blob/master/qpdflib/qpdfwidget.h) class. You can use those to change pages:
`pPdfWidget->setPage(pPdfWidget->page() + 1); // next page`
`pPdfWidget->setPage(pPdfWidget->page() - 1); // previous page`
